storage:
  host: "postgres"
  port: 5432
  database: "image-processor-db"
  user: "postgres"
  password: "postgres"
  migrations: true
  ssl_mode: "disable"

server:
  address: "0.0.0.0"
  port: "8080"
  timeout: "30s"
  idle_timeout: "120s"
  cors: true
  # allow_origins : "*"

message_broker:
  address: "kafka:9093"
  image_topic: "image"
  processor_group: "processor-group"
  broadcaster_group: "broadcaster-group"
  create_topic: true
  session_timeout: "30s"
  max_poll_interval: "5m"

s3